Create gas station
legafise/GasStation pull request #1
Opened 2020-06-09 12:11 UTC by legafise

2020-06-10 21:25 UTC, IvanYarochkin requested changes

2020-06-10 21:25 UTC, IvanYarochkin commented on src/main/java/com/lashkevich/station/entity/CarMake.java
> +    }
It's better to name markName rather than info.

2020-06-10 21:25 UTC, IvanYarochkin commented on src/main/java/com/lashkevich/station/entity/FillingStation.java
> +    private Lock LOCK = new ReentrantLock();
`lock` rather than `LOCK` since it's not a final variable.

2020-06-10 21:25 UTC, IvanYarochkin commented on src/main/java/com/lashkevich/station/entity/FillingStation.java
> +            throw new FillingException();
Add any message to the exception.

2020-06-10 21:40 UTC, legafise commented on src/main/java/com/lashkevich/station/entity/CarMake.java
> +    }
Done

2020-06-10 21:42 UTC, legafise commented on src/main/java/com/lashkevich/station/entity/FillingStation.java
> +    private Lock LOCK = new ReentrantLock();
Done

2020-06-11 09:26 UTC, legafise commented on src/main/java/com/lashkevich/station/entity/FillingStation.java
> +            throw new FillingException();
Done

2020-06-24 21:08 UTC, IvanYarochkin approved these changes

2020-06-24 21:10 UTC, IvanYarochkin approved these changes

2020-06-24 21:10 UTC, IvanYarochkin approved these changes

2020-06-24 22:22 UTC, IvanYarochkin approved these changes

2020-07-01 19:40 UTC, merged